### ISSUE TITLE
train.py fails

### ISSUE THREAD

**Issue by RomanHotsiy** [iborko/theano-conv-semantic#1]
Hi Ivan,
thanks for sharing your code.

But I can't run it :(

It fails with the following output:

```
$ python train.py      
INFO:__main__:... loading data
INFO:util:Succesfully loaded pickle ./data/MSRC/theano_datasets/x_train.bin
INFO:util:Succesfully loaded pickle ./data/MSRC/theano_datasets/y_train.bin
INFO:util:Succesfully loaded pickle ./data/MSRC/theano_datasets/x_test.bin
INFO:util:Succesfully loaded pickle ./data/MSRC/theano_datasets/y_test.bin
INFO:__main__:Image shape is (216, 320)
INFO:__main__:Train set has 3 images
INFO:__main__:Input train set has shape of (3, 216, 320) 
INFO:__main__:Test set has 3 images
INFO:__main__:Input test set has shape of (3, 216, 320) 
INFO:__main__:Batch size 1
INFO:__main__:Number of train batches 3
INFO:__main__:Number of test batches 3
INFO:__main__:... building network
INFO:helpers.build_net:... building the model
INFO:helpers.layers.conv:Creating conv layer with filter shape (20, 1, 7, 7),image shape: (1, 1, 216, 320)
INFO:helpers.layers.conv:Layer fully connected
INFO:helpers.layers.conv:Creating conv layer with filter shape (12, 2, 7, 7),image shape: (1, 2, 216, 320)
INFO:helpers.layers.conv:Layer fully connected
INFO:helpers.layers.conv:Creating conv layer with filter shape (128, 16, 5, 5),image shape: (1, 32, 105, 157)
INFO:helpers.layers.conv:Layer sparse (random) connected
INFO:helpers.layers.conv:Creating conv layer with filter shape (256, 64, 3, 3),image shape: (1, 128, 50, 76)
INFO:helpers.layers.conv:Layer sparse (random) connected
INFO:helpers.layers.conv:Creating conv layer with filter shape (256, 128, 3, 3),image shape: (1, 256, 48, 74)
INFO:helpers.layers.conv:Layer sparse (random) connected
INFO:__main__:Image out shape is (46, 72)
INFO:helpers.data_helper:Reshaping data_y, old shape is (532, 46, 72)
INFO:helpers.data_helper:Reshaping data_y, new shape is (532, 3312)
INFO:helpers.data_helper:Reshaping data_y, old shape is (59, 46, 72)
INFO:helpers.data_helper:Reshaping data_y, new shape is (59, 3312)
INFO:__main__:... building model
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    evaluate_conv('./data/MSRC/theano_datasets/', n_epochs=220, batch_size=1)
  File "train.py", line 140, in evaluate_conv
    y: y_test_shared_i32[index * batch_size: (index + 1) * batch_size]
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 489, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 228, in rebuild_collect_shared
    cloned_v = clone_v_get_shared_updates(v, copy_inputs_over)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 92, in clone_v_get_shared_updates
    clone_a(v.owner, copy_inputs_over)
  ... a lot of similar lines
    clone_a(v.owner, copy_inputs_over)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 135, in clone_a
    strict=rebuild_strict)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 211, in clone_with_new_inputs
    new_inputs[i] = curr.type.filter_variable(new)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 218, in filter_variable
    self=self)
TypeError: Cannot convert Type TensorType(float64, 3D) (of Variable Subtensor{int64:int64:}.0) into Type TensorType(float64, 4D). You can try to manually convert Subtensor{int64:int64:}.0 into a TensorType(float64, 4D).
```

I'm very new to Theano, so I can't understand what's wrong.
Do you have any idea what I'm doing wrong?

Thanks a lot.

**Comment by iborko** [comment]
This problem is now fixed.
